# ============================================
# DentaMate GitHub Actions Workflow Template
# ============================================
# Usage: Copy this to .github/workflows/ in your service repo
# Automatically builds Docker image and deploys to Render
# ============================================

name: Build & Deploy to Render

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME will be: ghcr.io/abysonjose/repo-name
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (for better caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Extract metadata (tags, labels)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Step 6: Trigger Render deployment
      - name: Trigger Render deploy
        if: success()
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

      # Step 7: Deployment notification
      - name: Deployment status
        if: success()
        run: |
          echo "✅ Docker image built and pushed successfully"
          echo "✅ Render deployment triggered"
          echo "🚀 Check Render dashboard for deployment progress"
