# ============================================
# DentaMate GitHub Actions Workflow Template (With Tests)
# ============================================
# Usage: Copy this to .github/workflows/ in your service repo
# Runs tests before building and deploying
# ============================================

name: Test, Build & Deploy to Render

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Job 1: Run tests
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # For Node.js services
      - name: Setup Node.js (if Node.js service)
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (Node.js)
        if: hashFiles('package.json') != ''
        run: npm ci

      - name: Run tests (Node.js)
        if: hashFiles('package.json') != ''
        run: npm test

      # For Python services
      - name: Setup Python (if Python service)
        if: hashFiles('requirements.txt') != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies (Python)
        if: hashFiles('requirements.txt') != ''
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests (Python)
        if: hashFiles('requirements.txt') != ''
        run: pytest

  # Job 2: Build and deploy (only on main branch)
  build-and-deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger Render deploy
        if: success()
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Deployment status
        if: success()
        run: |
          echo "✅ Tests passed"
          echo "✅ Docker image built and pushed"
          echo "✅ Render deployment triggered"
